name: Fetch Concert crolling and send Email

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/5 * * * *"  # 5분마다 실행
  push:
    branches: 
      - main

jobs:
  fetch_concert:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
